export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_STATUS = "USER_LOGIN_STATUS";

export const USER_REGISTATION = "USER_REGISTATION";
export const USER_REGISTATION_SUCCESS = "USER_REGISTATION_SUCCESS";
export const USER_REGISTATION_FAIL = "USER_REGISTATION_FAIL";
export const USER_REGISTATION_STATUS = "USER_REGISTATION_STATUS";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCESS = "OTP_SUCESS";
export const OTP_FAIL = "OTP_FAIL";
