export const colors = {
  pink: "#efb5a3",
  peach: "#f57e7e",
  green: "#315f72",
  black: "black",
  white: "white",
  gray: "gray",
  borderColor: "#ccc",
  dotcolor: "#FFEE58",
  inactive: "#90A4AE",
  wpGreen: "#25D366",
  red: "red",
  offWhite: "#ccc",
  offPink: "#F8C8DC",
  blue: "#0000e6",
};
