export const String = {
  Login: "Login",
  Email: "Enter Email",
  Password: "Password",
  Submit: "Submit",
  welcome: "Welcome!!",
  Registation: "Registration",
  Email_Validation: "Email Validation",
  continue: "Continue",
  Register: "Register",
  FirstName: " First Name",
  LastName: "Last Name",
  Phone: "Phone Number",
  create: "Create",
  cpassword: "Confirm Password",
  Name: "Name",
  ThirdParty: "THIRDPARTY",
  withdraw: "WITHDRAW",
  withdrawCoins: "WITHDRAW COINS",
  deposite: "DEPOSITE",
  CountryCode: "Country Code",
  Country: "Country",
  Depositcoin: "DEPOSITE COINS",
  PaymentMethod: "PAYMENT METHOD",
  Dashboard: "DASHBOARD",
};
