export const String = {
  Login: "Login",
  Email: "Enter Email",
  Password: "Password",
  Submit: "Submit",
  welcome: "Welcome!!",
  Registation: "Registration",
  Email_Validation: "Email Validation",
  continue: "Continue",
  Register: "Register",
  createAccount: "Create Account",
  FirstName: " First Name",
  LastName: "Last Name",
  Phone: "Phone Number",
  create: "Create",
  cpassword: "Confirm Password",
  Name: "Name",
  ThirdParty: "THIRDPARTY",
  withdraw: "WITHDRAW",
  withdrawCoins: "WITHDRAW COINS",
  deposite: "DEPOSITE",
  CountryCode: "Country Code",
  Country: "Country",
  Depositcoin: "DEPOSITE COINS",
  PaymentMethod: "PAYMENT METHOD",
  Dashboard: "DASHBOARD",
  cancel: "Cancel",
  Enter_OTP: "Enter OTP",
  Clear: "Clear",
  Verify_OTP: "Verify OTP",
  otpTitle: "OTP Verification",
  Signup: "Sign-up",
  resetPassword: "Reset Password",
  forgetPassword: "Forgot Password",
  back: "Back",
  Agree_Join: "Agree & Join",
  JoinNow: "Join Now ",
  Submit2: "SUBMIT",
  sendOtp: "SEND OTP",
  Resend: "Resend",
  ResetPassword: "Reset Password",
  subtitle: " Enter your email to reset your password",
  send: "Send",
};
